// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWICYEW-1ej3almam0374xTnT3sowFTLM',
    appId: '1:205556178965:web:9502fb241fbb75a1a52e1c',
    messagingSenderId: '205556178965',
    projectId: 'ecommerce-d04c3',
    authDomain: 'ecommerce-d04c3.firebaseapp.com',
    storageBucket: 'ecommerce-d04c3.firebasestorage.app',
    measurementId: 'G-REBK0H6Y0F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBS08G-nXozWJoy616DSPShYEC57sWb5gs',
    appId: '1:205556178965:android:c950e6d9c19be23fa52e1c',
    messagingSenderId: '205556178965',
    projectId: 'ecommerce-d04c3',
    storageBucket: 'ecommerce-d04c3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0ybz5QLdNiIyk4AocNMYUqGxls5bV9C8',
    appId: '1:205556178965:ios:63c9cbe96336c543a52e1c',
    messagingSenderId: '205556178965',
    projectId: 'ecommerce-d04c3',
    storageBucket: 'ecommerce-d04c3.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0ybz5QLdNiIyk4AocNMYUqGxls5bV9C8',
    appId: '1:205556178965:ios:63c9cbe96336c543a52e1c',
    messagingSenderId: '205556178965',
    projectId: 'ecommerce-d04c3',
    storageBucket: 'ecommerce-d04c3.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWICYEW-1ej3almam0374xTnT3sowFTLM',
    appId: '1:205556178965:web:5e437e8be179eec3a52e1c',
    messagingSenderId: '205556178965',
    projectId: 'ecommerce-d04c3',
    authDomain: 'ecommerce-d04c3.firebaseapp.com',
    storageBucket: 'ecommerce-d04c3.firebasestorage.app',
    measurementId: 'G-1RXWTCWFPW',
  );
}
